name: ITC
version: 1.5.1
date: 2022-03-01
description: |
    Interactive Todd-Coxeter

authors:
    - name: Volkmar Felsch
      url: http://www.math.rwth-aachen.de/LDFM/homes/Volkmar.Felsch/
    - name: Ludger Hippe
    - name: Joachim Neubüser
      url: http://www.math.rwth-aachen.de/LDFM/homes/Joachim.Neubueser/

maintainers:
    - name: The GAP Team
      url: mailto:support@gap-system.org

GAP: "4.8"

needed-pkgs:
    - name: "xgap"
      version: ">= 4.02"
      url: "https://gap-packages.github.io/xgap"

www: https://gap-packages.github.io/itc/
readme: README
packageinfo: https://gap-packages.github.io/itc/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/itc/releases/download/v1.5.1/itc-1.5.1.tar.gz

abstract: |
    This <span class="pkgname">GAP</span> package provides    access to interactive Todd-Coxeter computations    with finitely presented groups.

status: accepted
doc-html: htm/chapters.htm
doc-pdf: doc/manual.pdf
keywords: |
    interactive Todd-Coxeter, coset enumeration.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>FHNT22</span>]   <b class='BibAuthor'>Felsch, V., Hippe, L., Neubüser, J. and GAP Team, T.</b>,
     <i class='BibTitle'>ITC, Interactive Todd-Coxeter,
             Version 1.5.1</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/itc/">https://gap-packages.github.io/itc/</a></span>.
    </p>
    

bibtex: |
    @misc{ ITC1.5.1,
      author =           {Felsch,  V. and Hippe, L. and Neub{\"u}ser, J. and GAP
                          Team, T.},
      title =            {{ITC}, Interactive Todd-Coxeter, {V}ersion 1.5.1},
      month =            {Mar},
      year =             {2022},
      note =             {Refereed GAP package},
      howpublished =     {\href            {https://gap-packages.github.io/itc/}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{itc/}}},
      keywords =         {interactive Todd-Coxeter; coset enumeration},
      printedkey =       {FHNT22}
    }

